UserProject/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UserProject.Models
{
    public class Location
    {
        public int LocationId { get; set; }
        [Required]
        public string LocationName { get; set; }
        public string LocationImage { get; set; }
        public List<Multiplex> Multiplexes { get; set; }
    }
}

UserProject/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UserProject.Models;

namespace AdminProject.Controllers
{
    public class LocationController : Controller
    {
        FinalProjectDataDbContext context = new FinalProjectDataDbContext();
        public IActionResult Index()
        {
            {
                var locations = context.Locations.ToList();
                return View(locations);
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Location location = context.Locations.Find(id);

            return View(location);
        }

        [HttpPost]
        public ActionResult Delete(int id, Location a1)
        {
            var location = context.Locations.Where(x => x.LocationId == id).SingleOrDefault();
            context.Locations.Remove(location);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ViewResult Create()
        {
            var locations = context.Locations.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind("LocationName")] Location a1)
        {
            if (ModelState.IsValid)
            {
                context.Locations.Add(a1);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(a1);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            Location location = context.Locations.Where(x => x.LocationId == id).SingleOrDefault();
            return View(location);
        }
        [HttpPost]
        public ActionResult Edit(int id, Location a1)
        {
            Location location = context.Locations.Where(x => x.LocationId == id).SingleOrDefault();

            location.LocationName = a1.LocationName;
            location.LocationImage = a1.LocationImage;
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ViewResult Details(int id)
        {
            Location location = context.Locations.Where(x => x.LocationId == id).SingleOrDefault();
            return View(location);
        }
    }
}

UserProject/Controllers/MultiplexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserProject.Models;

namespace UserProject.Controllers
{
    public class MultiplexController : Controller
    {
        FinalProjectDataDbContext context = new FinalProjectDataDbContext();
        public IActionResult Index()
        {
            var multiplexes = context.Multiplexes.ToList();
            return View(multiplexes);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Multiplex multiplex = context.Multiplexes.Find(id);

            return View(multiplex);
        }
        [HttpPost]
        public ActionResult Delete(int id, Multiplex m1)
        {
            var author = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            context.Multiplexes.Remove(author);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Multiplex multiplex = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            return View(multiplex);
        }

        [HttpPost]
        public ActionResult Edit(int id, Multiplex m1)
        {
            Multiplex multiplex = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            multiplex.MultiplexName = m1.MultiplexName;
            multiplex.MultiplexDescription = m1.MultiplexDescription;
            multiplex.MultiplexImage = m1.MultiplexImage;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            Multiplex multiplex = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            return View(multiplex);
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.location = new SelectList(context.Locations, "LocationId", "LocationName");
            var multiplexes = context.Multiplexes.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind("MultiplexName", "MultiplexDescription")] Multiplex m1)
        {
            if (ModelState.IsValid)
            {
                context.Multiplexes.Add(m1);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(m1);
        }
    }
}

UserProject/Views/Location/Create.cshtml
@model UserProject.Models.Location
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>CREATE</b></h2>
<br />


<form asp-action="Create" asp-controller="Location">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label for="LocationName"><b>Location Name</b></label>
        <input type="text" asp-for="LocationName" class="form-control" placeholder="Enter Location Name">
        <span asp-validation-for="LocationName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="LocationName"><b>Location Image</b></label>
        <input type="text" asp-for="LocationImage" class="form-control" placeholder="Enter Location Image">
        <span asp-validation-for="LocationImage" class="text-danger"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
    @*@Html.ActionLink("back to list", "Index")*@
    <a asp-controller="Location" asp-action="Index" class="btn btn-light"><b>Back To List</b></a>
</form>

UserProject/Views/Location/Delete.cshtml
@model UserProject.Models.Location
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>DELETE</b></h2>
<br />
<h4>Are you sure you want to delete this?</h4>
</br>
<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">


        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.LocationName)</b>: @Html.DisplayFor(model => model.LocationName)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.LocationImage)</b>: @Html.DisplayFor(model => model.LocationImage)</li>

    </ul>
</div>
<br />

@using (Html.BeginForm("Delete", "Location", FormMethod.Post))
{
    <p>
        <input type="submit" value="Delete" , class="btn btn-danger" />
        <a asp-controller="Location" asp-action="Index" class="btn btn-primary">Back To List</a>
    </p>
}

UserProject/Views/Location/Details.cshtml
@model UserProject.Models.Location
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>Location Details</b></h2>
<br />

@*@Html.DisplayNameFor(model => model.MultiplexId);
    @Html.DisplayFor(model => model.MultiplexId);
    <br />

    @Html.DisplayNameFor(model => model.MultiplexName);
    @Html.DisplayFor(model => model.MultiplexName);
    <br />

    @Html.DisplayNameFor(model => model.MultiplexDescription);
    @Html.DisplayFor(model => model.MultiplexDescription);
    <br />*@

<div class="col-md-12">
    <div class="card">
            <ul class="list-group list-group-flush">

                <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.LocationId)</b>: @Html.DisplayFor(model => model.LocationId)</li>
                <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.LocationName)</b>: @Html.DisplayFor(model => model.LocationName)</li>
            </ul>
        </div>
    </div>
        <br />
        <div class="col-md-12">
            <a asp-controller="Location" asp-action="Index" class="btn btn-primary">Back To List</a>
            </div>

UserProject/Views/Location/Edit.cshtml
@model UserProject.Models.Location
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>EDIT</b></h2>
<br />
<form asp-action="Edit" asp-controller="Location">
    <div class="form-group">
        <label asp-for="LocationName"><b>Location Name</b></label>
        <input type="text" class="form-control" asp-for="LocationName" placeholder="Enter Location Name">

    </div>
    <div class="form-group">
        <label asp-for="LocationImage"><b>Location Image</b></label>
        <input type="text" class="form-control" asp-for="LocationImage" placeholder="Enter Location Image">

    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-controller="Location" asp-action="Index" class="btn btn-light"><b>Back To List</b></a>
</form>

@*@using (Html.BeginForm("Edit", "Multiplex", FormMethod.Post))
    {

        @Html.LabelFor(model => model.MultiplexName)
        @Html.EditorFor(model => model.MultiplexName)
        <br />


        <br />*@

UserProject/Views/Location/Index.cshtml
@model IEnumerable<UserProject.Models.Location>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>Index</b></h2>
<p>
    <a asp-controller="Location" asp-action="Create" class="btn btn-primary">Create New Location</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LocationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LocationName)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.LocationId)
                </td>
                <td>
                    @Html.DisplayFor(model => item.LocationName)
                </td>
                <td>
                    <a asp-controller="Location" asp-action="Details" asp-route-id="@item.LocationId" class="btn btn-info">Details</a>
                    <a asp-controller="Location" asp-action="Edit" asp-route-id="@item.LocationId" class="btn btn-success">Edit</a>
                    <a asp-controller="Location" asp-action="Delete" asp-route-id="@item.LocationId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>