UserProject/Models/Movie.cs
using AdminProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UserProject.Models
{
    public class Movie
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public double MoviePrice { get; set; }
        public string MovieImage { get; set; }
        public string MovieDuration { get; set; }
        public string MovieDescription { get; set; }
        public int MultiplexId { get; set; }
        public DateTime MovieDate { get; set; }
        public Multiplex Multiplex { get; set; }
        public MovieDetail MovieDetail { get; set; }
        public Review Reviews { get; set; }

        //public List<Booking> Bookings { get; set; }



    }
}

UserProject/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserProject.Models;

namespace AdminProject.Controllers
{
    public class MovieController : Controller
    {
        FinalProjectDataDbContext context = new FinalProjectDataDbContext();
        public IActionResult Index()
        {
            var movies = context.Movies.ToList();
            return View(movies);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Movie movie = context.Movies.Find(id);

            return View(movie);
        }
        [HttpPost]
        public ActionResult Delete(int id, Movie m1)
        {
            var author = context.Movies.Where(x => x.MovieId == id).SingleOrDefault();
            context.Movies.Remove(author);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Movie movie = context.Movies.Where(x => x.MovieId == id).SingleOrDefault();
            return View(movie);
        }

        [HttpPost]
        public ActionResult Edit(int id, Movie m1)
        {
            Movie movie = context.Movies.Where(x => x.MovieId == id).SingleOrDefault();
            movie.MovieName = m1.MovieName;
            movie.MoviePrice = m1.MoviePrice;
            movie.MovieDescription = m1.MovieDescription;
            movie.MovieDuration = m1.MovieDuration;
            movie.MovieImage = m1.MovieImage;
            //movie.AuditoriumId = m1.AuditoriumId;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            Movie movie = context.Movies.Where(x => x.MovieId == id).SingleOrDefault();
            return View(movie);
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.auditorium = new SelectList(context.Auditoriums, "AuditoriumId", "AuditoriumName");
            var movies = context.Movies.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Movie m1)
        {
            context.Movies.Add(m1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

UserProject/Controllers/MultiplexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserProject.Models;

namespace UserProject.Controllers
{
    public class MultiplexController : Controller
    {
        FinalProjectDataDbContext context = new FinalProjectDataDbContext();
        public IActionResult Index()
        {
            var multiplexes = context.Multiplexes.ToList();
            return View(multiplexes);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Multiplex multiplex = context.Multiplexes.Find(id);

            return View(multiplex);
        }
        [HttpPost]
        public ActionResult Delete(int id, Multiplex m1)
        {
            var author = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            context.Multiplexes.Remove(author);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Multiplex multiplex = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            return View(multiplex);
        }

        [HttpPost]
        public ActionResult Edit(int id, Multiplex m1)
        {
            Multiplex multiplex = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            multiplex.MultiplexName = m1.MultiplexName;
            multiplex.MultiplexDescription = m1.MultiplexDescription;
            multiplex.MultiplexImage = m1.MultiplexImage;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ViewResult Details(int id)
        {
            Multiplex multiplex = context.Multiplexes.Where(x => x.MultiplexId == id).SingleOrDefault();
            return View(multiplex);
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.location = new SelectList(context.Locations, "LocationId", "LocationName");
            var multiplexes = context.Multiplexes.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind("MultiplexName", "MultiplexDescription")] Multiplex m1)
        {
            if (ModelState.IsValid)
            {
                context.Multiplexes.Add(m1);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(m1);
        }
    }
}

UserProject/Views/Movie/Create.cshtml
@model UserProject.Models.Movie
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>CREATE</b></h2>
<br />


<form asp-action="Create" asp-controller="Movie">
    @*<div class="form-group">
        <label asp-for="AuditoriumId"><b>Auditorium Name</b></label>
        <select class="custom-select my-1 mr-sm-2" asp-for="AuditoriumId" asp-items="ViewBag.auditorium"></select>
    </div>*@
    <label asp-for="MovieName"><b>Movie Name</b></label>
    <input type="text" class="form-control" asp-for="MovieName" placeholder="Enter Movie Name">
    <div>
        <label asp-for="MoviePrice"><b>Movie Price</b></label>
        <input type="text" class="form-control" asp-for="MoviePrice" placeholder="Enter Movie Price">
    </div>
    <div>
        <label asp-for="MovieDescription"><b>Movie Description</b></label>
        <input type="text" class="form-control" asp-for="MovieDescription" placeholder="Enter Movie Description">
    </div>
    <div>
        <label asp-for="MovieDuration"><b>Movie Duration</b></label>
        <input type="text" class="form-control" asp-for="MovieDuration" placeholder="Enter Movie Duration">
    </div>
    <div>
        <label asp-for="MovieImage"><b>Movie Image</b></label>
        <input type="text" class="form-control" asp-for="MovieImage" placeholder="Enter Movie Image">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
    @*@Html.ActionLink("back to list", "Index")*@
    <a asp-controller="Movie" asp-action="Index" class="btn btn-light"><b>Back To List</b></a>
</form>

UserProject/Views/Movie/Delete.cshtml
@model UserProject.Models.Movie
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>DELETE</b></h2>
<br />
<h4>Are you sure you want to delete this?</h4>
</br>
<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">

        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieName)</b>: @Html.DisplayFor(model => model.MovieName)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MoviePrice)</b>: @Html.DisplayFor(model => model.MoviePrice)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieDescription)</b>: @Html.DisplayFor(model => model.MovieDescription)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieDuration)</b>: @Html.DisplayFor(model => model.MovieDuration)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieImage)</b>: @Html.DisplayFor(model => model.MovieImage)</li>
        @*<li class="list-group-item"><b>@Html.DisplayNameFor(model => model.AuditoriumId)</b>: @Html.DisplayFor(model => model.AuditoriumId)</li>*@
    </ul>
</div>
<br />

@using (Html.BeginForm("Delete", "Movie", FormMethod.Post))
{
    <p>
        <input type="submit" value="Delete" , class="btn btn-danger" />
        @*@Html.ActionLink("back to list", "Index")*@
        <a asp-controller="Movie" asp-action="Index" class="btn btn-primary">Back To List</a>
    </p>
}

UserProject/Views/Movie/Details.cshtml
@model UserProject.Models.Movie
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>Movie Details</b></h2>
<br />

<div class="col-md-12">
    <div class="card">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieId)</b>: @Html.DisplayFor(model => model.MovieId)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieName)</b>: @Html.DisplayFor(model => model.MovieName)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MoviePrice)</b>: @Html.DisplayFor(model => model.MoviePrice)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieDescription)</b>: @Html.DisplayFor(model => model.MovieDescription)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieDuration)</b>: @Html.DisplayFor(model => model.MovieDuration)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MovieImage)</b>: @Html.DisplayFor(model => model.MovieImage)</li>
            @*<li class="list-group-item"><b>@Html.DisplayNameFor(model => model.AuditoriumId)</b>: @Html.DisplayFor(model => model.AuditoriumId)</li>*@
        </ul>
        </div>
    </div>
        <br />
        <div class="col-md-12">
            <a asp-controller="Movie" asp-action="Index" class="btn btn-primary">Back To List</a>
            </div>

UserProject/Views/Movie/Edit.cshtml
@model UserProject.Models.Movie
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>EDIT</b></h2>
<br />
<form asp-action="Edit" asp-controller="Movie">
    <div class="form-group">
        <label asp-for="MovieName"><b>Movie Name</b></label>
        <input type="text" class="form-control" asp-for="MovieName" placeholder="Enter Movie Name">

        <label asp-for="MoviePrice"><b>Movie Price</b></label>
        <input type="text" class="form-control" asp-for="MoviePrice" placeholder="Enter Movie Price">
        <label asp-for="MovieDescription"><b>Movie Description</b></label>
        <input type="text" class="form-control" asp-for="MovieDescription" placeholder="Enter Movie Description">
        <label asp-for="MovieDuration"><b>Movie Duration</b></label>
        <input type="text" class="form-control" asp-for="MovieDuration" placeholder="Enter Movie Duration">
        <label asp-for="MovieImage"><b>Movie Image</b></label>
        <input type="text" class="form-control" asp-for="MovieImage" placeholder="Enter Movie Image">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-controller="Multiplex" asp-action="Index" class="btn btn-light"><b>Back To List</b></a>
</form>

@*@using (Html.BeginForm("Edit", "Multiplex", FormMethod.Post))
    {

        @Html.LabelFor(model => model.MultiplexName)
        @Html.EditorFor(model => model.MultiplexName)
        <br />


        <br />*@

UserProject/Views/Movie/Index.cshtml
@model IEnumerable<UserProject.Models.Movie>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>Index</b></h2>

<p>
    <a asp-controller="Movie" asp-action="Create" class="btn btn-primary">Create New Movie</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MovieId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MovieName)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.AuditoriumId)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MovieName)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.AuditoriumId)
            </td>*@
            <td>
                <a asp-controller="Movie" asp-action="Details" asp-route-id="@item.MovieId" class="btn btn-info">Details</a>
                <a asp-controller="Movie" asp-action="Edit" asp-route-id="@item.MovieId" class="btn btn-success">Edit</a>
                <a asp-controller="Movie" asp-action="Delete" asp-route-id="@item.MovieId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>