UserProject/Models/Auditorium.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UserProject.Models
{
    public class Auditorium
    {
        public int AuditoriumId { get; set; }
        public string AuditoriumName { get; set; }
        public string AuditoriumDescription { get; set; }
        public int Seats { get; set; }
        public string Time1 { get; set; }
        public string Time2 { get; set; }
        public string Time3 { get; set; }
        public int MultiplexId { get; set; }
        public Multiplex Multiplex { get; set; }
      
    }
}

UserProject/Controllers/AuditoriumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UserProject.Models;

namespace AdminProject.Controllers
{
    public class AuditoriumController : Controller
    {
        FinalProjectDataDbContext context = new FinalProjectDataDbContext();
        public IActionResult Index()
        {
            var auditoriums = context.Auditoriums.ToList();
            return View(auditoriums);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Auditorium auditorium = context.Auditoriums.Find(id);

            return View(auditorium);
        }

        [HttpPost]
        public ActionResult Delete(int id, Auditorium a1)
        {
            var auditorium = context.Auditoriums.Where(x => x.AuditoriumId == id).SingleOrDefault();
            context.Auditoriums.Remove(auditorium);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.multiplex = new SelectList(context.Multiplexes, "MultiplexId", "MultiplexName");
            var auditoriums = context.Auditoriums.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Auditorium a1)
        {
            context.Auditoriums.Add(a1);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

            Auditorium auditorium = context.Auditoriums.Where(x => x.AuditoriumId == id).SingleOrDefault();
            return View(auditorium);
        }
        [HttpPost]
        public ActionResult Edit(int id, Auditorium a1)
        {
            Auditorium auditorium = context.Auditoriums.Where(x => x.AuditoriumId == id).SingleOrDefault();

            auditorium.AuditoriumName = a1.AuditoriumName;
            auditorium.AuditoriumDescription = a1.AuditoriumDescription;
            auditorium.Seats = a1.Seats;
            auditorium.Time1 = a1.Time1;
            auditorium.Time2 = a1.Time2;
            auditorium.Time3 = a1.Time3;
            auditorium.MultiplexId = a1.MultiplexId;
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ViewResult Details(int id)
        {
            Auditorium auditorium = context.Auditoriums.Where(x => x.AuditoriumId == id).SingleOrDefault();
            return View(auditorium);
        }
    }
}
    

UserProject/Views/Auditorium/Create.cshtml
@model UserProject.Models.Auditorium
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>CREATE</b></h2>
<br />


<form asp-action="Create" asp-controller="Auditorium">
    <div class="form-group">
            <label asp-for="MultiplexId"><b>Multiplex Name</b></label>
            <select class="custom-select my-1 mr-sm-2" asp-for="MultiplexId" asp-items="ViewBag.multiplex"></select>
        </div>
        <label for="AuditoriumName"><b>Auditorium Name</b></label>
        <input type="text" asp-for="AuditoriumName" class="form-control" placeholder="Enter Auditorium Name">
        <label for="AuditoriumDescription"><b>Auditorium Description</b></label>
        <input type="text" asp-for="AuditoriumDescription" class="form-control" placeholder="Enter Auditorium Description">
        <label for="Seats"><b>Seats</b></label>
        <input type="text" asp-for="Seats" class="form-control" placeholder="Enter No.of Seats">
        <label for="Time1"><b>Time1</b></label>
        <input type="text" asp-for="Time1" class="form-control" placeholder="Enter Time1">
        <label for="Time2"><b>Time2</b></label>
        <input type="text" asp-for="Time2" class="form-control" placeholder="Enter Time2">
        <label for="Time3"><b>Time3</b></label>
        <input type="text" asp-for="Time3" class="form-control" placeholder="Enter Time3">
       
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
    @*@Html.ActionLink("back to list", "Index")*@
    <a asp-controller="Auditorium" asp-action="Index" class="btn btn-light"><b>Back To List</b></a>
</form>

UserProject/Views/Auditorium/Delete.cshtml
@model UserProject.Models.Auditorium
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>DELETE</b></h2>
<br />
<h4>Are you sure you want to delete this?</h4>

<div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">


        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.AuditoriumName)</b>: @Html.DisplayFor(model => model.AuditoriumName)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.AuditoriumDescription)</b>: @Html.DisplayFor(model => model.AuditoriumDescription)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Seats)</b>: @Html.DisplayFor(model => model.Seats)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Time1)</b>: @Html.DisplayFor(model => model.Time1)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Time2)</b>: @Html.DisplayFor(model => model.Time2)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Time3)</b>: @Html.DisplayFor(model => model.Time3)</li>
        <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MultiplexId)</b>: @Html.DisplayFor(model => model.MultiplexId)</li>
    </ul>
</div>
<br />

@using (Html.BeginForm("Delete", "Auditorium", FormMethod.Post))
{
    <p>
        <input type="submit" value="Delete" , class="btn btn-danger" />
        <a asp-controller="Auditorium" asp-action="Index" class="btn btn-primary">Back To List</a>
    </p>
}

UserProject/Views/Auditorium/Details.cshtml
@model UserProject.Models.Auditorium
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>Auditorium Details</b></h2>
<br />

<div class="col-md-12">
    <div class="card">
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.AuditoriumId)</b>: @Html.DisplayFor(model => model.AuditoriumId)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.AuditoriumName)</b>: @Html.DisplayFor(model => model.AuditoriumName)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.AuditoriumDescription)</b>: @Html.DisplayFor(model => model.AuditoriumDescription)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Seats)</b>: @Html.DisplayFor(model => model.Seats)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Time1)</b>: @Html.DisplayFor(model => model.Time1)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Time2)</b>: @Html.DisplayFor(model => model.Time2)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.Time3)</b>: @Html.DisplayFor(model => model.Time3)</li>
            <li class="list-group-item"><b>@Html.DisplayNameFor(model => model.MultiplexId)</b>: @Html.DisplayFor(model => model.MultiplexId)</li>

        </ul>
        </div>
    </div>
        <br />
        <div class="col-md-12">
            <a asp-controller="Auditorium" asp-action="Index" class="btn btn-primary">Back To List</a>
            </div>

UserProject/Views/Auditorium/Edit.cshtml
@model UserProject.Models.Auditorium
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>EDIT</b></h2>
<br />
<form asp-action="Edit" asp-controller="Auditorium">
    <div class="form-group">
        <label asp-for="AuditoriumName"><b>Auditorium Name</b></label>
        <input type="text" class="form-control" asp-for="AuditoriumName" placeholder="Enter Auditorium Name">

        <label asp-for="AuditoriumDescription"><b>Auditorium Description</b></label>
        <input type="text" class="form-control" asp-for="AuditoriumDescription" placeholder="Enter Auditorium Description">

        <label asp-for="Seats"><b>Seats</b></label>
        <input type="text" class="form-control" asp-for="Seats" placeholder="Enter Seats">

        <label asp-for="Time1"><b>Time1</b></label>
        <input type="text" class="form-control" asp-for="Time1" placeholder="Enter Time1">

        <label asp-for="Time2"><b>Time2</b></label>
        <input type="text" class="form-control" asp-for="Time2" placeholder="Enter Time2">

        <label asp-for="Time3"><b>Time3</b></label>
        <input type="text" class="form-control" asp-for="Time3" placeholder="Enter Time3">

        <label asp-for="MultiplexId"><b>MultiplexId</b></label>
        <input type="text" class="form-control" asp-for="MultiplexId" placeholder="Enter MultiplexId">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <a asp-controller="Auditorium" asp-action="Index" class="btn btn-light"><b>Back To List</b></a>
</form>

UserProject/Views/Auditorium/Index.cshtml
@model IEnumerable<UserProject.Models.Auditorium>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><b>Index</b></h2>
<p>
    <a asp-controller="Auditorium" asp-action="Create" class="btn btn-primary">Create New Auditorium</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AuditoriumId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuditoriumName)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.MultiplexId)
            </th>

            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(model => item.AuditoriumId)
            </td>
            <td>
                @Html.DisplayFor(model => item.AuditoriumName)
            </td>
        
            <td>
                @Html.DisplayFor(model => item.MultiplexId)
            </td>

            <td>
                <a asp-controller="Auditorium" asp-action="Details" asp-route-id="@item.AuditoriumId" class="btn btn-info">Details</a>
                <a asp-controller="Auditorium" asp-action="Edit" asp-route-id="@item.AuditoriumId" class="btn btn-success">Edit</a>
                <a asp-controller="Auditorium" asp-action="Delete" asp-route-id="@item.AuditoriumId" class="btn btn-danger">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>